name: tables_io
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy>=1.21.0
  - astropy
  - h5py>=2.9=*mpi_openmpi*
  - pandas
  - pyarrow
  - pytables
  - mpi4py
  - hdf5=*=*mpi_openmpi*
  - pylint
  - pytest
  - pytest-cov
  - jupyter
  - pip
  - setuptools
  - coverage
  - flake8
  - click
  - jax
  - jaxlib
